version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: bahaev-as-netology-prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - bahaev-as-my-netology-hw
    ports:
      - "9090:9090"
    restart: unless-stopped

volumes:
  prometheus-data:

networks:
  bahaev-as-my-netology-hw:
    external: true
