version: '3.9'

services:
  pushgateway:
    image: prom/pushgateway:v1.6.2
    container_name: bahaev-as-netology-pushgateway
    ports:
      - 9091:9091
    networks:
      - bahaev-as-my-netology-hw
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  bahaev-as-my-netology-hw:
    external: true